---
# tasks file for avise_vmware

- name: Check ansible version
  when:
    - ansible_version.full is version_compare('2.4', '<')
  debug: msg="This role works best with ansible version 2.4 or greater. It is recommended to use the latest ansible version for the best experience."

- name: Avi SE | Set facts
  block:
    - set_fact: se_ova_deploy=true
    - set_fact: se_autoregister=false
      when: se_auth_token != None
    - set_fact: se_ova_deploy=false
      when: se_vmw_ova_path != None

- name: Avi SE | Requirements
  include: requirements.yml
  when: not se_skip_requirements

- name: Avi SE | Initial Data
  include: initial_data.yml

- name: Avi SE | VMware | Autoregistration
  include: autoregistration.yml
  when: se_autoregister

- name: Avi SE | Destroy Vm
  include: destroy_se.yml
  when: state == "absent"

- block:
    - name: Avi SE | VMware | Get OVA image
      include: ova_deploy.yml
      when: se_ova_deploy

    - name: Avi SE | VMware | Deploy SE VM
      deploy_se:
        ovftool_path: '{{ ovftool_path }}'
        vcenter_host: '{{ vcenter_host }}'
        vcenter_user: '{{ vcenter_user }}'
        vcenter_password: '{{ vcenter_password }}'
        ssl_verify: '{{ ssl_verify }}'
        state: '{{ state }}'
        se_vmw_datacenter: '{{ se_vmw_datacenter }}'
        se_vmw_cluster: '{{ se_vmw_cluster }}'
        se_vmw_datastore: '{{ se_vmw_datastore }}'
        se_vmw_ovf_networks: '{{ se_vmw_ovf_networks }}'
        se_vmw_disk_mode: '{{ se_vmw_disk_mode }}'
        se_vmw_ova_path: '{{ se_vmw_ova_path }}'
        se_vmw_vm_name: '{{ se_vmw_vm_name }}'
        se_vmw_power_on: '{{ se_vmw_power_on }}'
        se_vmw_vcenter_folder: '{{ se_vmw_vcenter_folder }}'
        se_vmw_mgmt_ip: '{{ se_vmw_mgmt_ip }}'
        se_vmw_mgmt_mask: '{{ se_vmw_mgmt_mask }}'
        se_vmw_default_gw: '{{ se_vmw_default_gw }}'
        se_vmw_sysadmin_public_key: '{{ se_vmw_sysadmin_public_key }}'
        se_auth_token: '{{ se_auth_token }}'
        se_cluster_uuid: '{{ se_cluster_uuid }}'
        se_master_ctl_ip: '{{ se_master_ctl_ip }}'
        se_vmw_number_of_cpus: '{{ se_vmw_number_of_cpus }}'
        se_vmw_cpu_reserved: '{{ se_vmw_cpu_reserved }}'
        se_vmw_memory: '{{ se_vmw_memory }}'
        se_vmw_memory_reserved: '{{ se_vmw_memory_reserved }}'
        se_vmw_disk_size: '{{ se_vmw_disk_size }}'
        se_vmw_ovf_properties: '{{ se_vmw_ovf_properties }}'
      delegate_to: localhost

    - name: Avi SE | Verify SE Deployment
      verify_se:
        se_master_ctl_ip: '{{ se_master_ctl_ip }}'
        se_master_ctl_username: '{{ se_master_ctl_username }}'
        se_master_ctl_password: '{{ se_master_ctl_password }}'
        se_master_ctl_version: '{{ se_master_ctl_version }}'
        se_cloud_name: '{{ se_cloud_name }}'
        se_group_name: '{{ se_group_name }}'
        se_tenant: '{{ se_tenant }}'
        se_vmw_vm_name: '{{ se_vmw_vm_name }}'
        se_vmw_mgmt_ip: '{{ se_vmw_mgmt_ip }}'
      register: verify_output
      delegate_to: localhost

    - debug: msg={{ verify_output.msg }}

    - name: Avi SE | Attach SE to SE group
      avi_api_session:
        controller: "{{ se_master_ctl_ip }}"
        username: "{{ se_master_ctl_username }}"
        password: "{{ se_master_ctl_password }}"
        tenant: "{{ se_tenant }}"
        api_version: "{{ se_master_ctl_version }}"
        http_method: patch
        data:
          add:
            se_group_ref: "/api/serviceenginegroup?name={{ se_group_name }}"
        path: "serviceengine/{{ verify_output.se_details.uuid }}" 
  when: state == "present"

